### ISSUE TITLE
NRF51 Software Serial dependency

### ISSUE THREAD

**Issue by insidecircuits** [adafruit/Adafruit_AHRS#12]
- Arduino board:  Arduino UNO
- atom + PlatformIO IDE
- install Adafruit AHRS library and compile **calibrated_orientation.ino** example

<img width="1309" alt="Screen Shot 2020-05-10 at 17 54 49" src="https://user-images.githubusercontent.com/2429087/81504051-87b35900-92e7-11ea-9cd8-006d7fa4f77b.png">

I think this can be easily fixed, it asks for a dependency even if the NRF51 library is not used.

**Comment by ladyada** [comment]
hi this is a known issue with platformio - @ivankravets can help you with this, there's a setting in platformio to ignore libraries :)
