### ISSUE TITLE
documenting the quaternion output of the NXP algorithm

### ISSUE THREAD

**Issue by jerabaul29** [adafruit/Adafruit_AHRS#20]
Looking at the code around the quaternion output for the NXP algorithm:

https://github.com/adafruit/Adafruit_AHRS/blob/1425f14fbd2312bc57bcb0bd9bd9372372eaf363/src/Adafruit_AHRS_NXPFusion.h#L86-L91

I am not sure of what referential transform this quaternion performs. Is it (X, Y, Z) to (North, East, Down), or some other but similar referential transform?

**Comment by ladyada** [comment]
here is a guide on it - https://scriptinghelpers.org/blog/how-to-think-about-quaternions
