### ISSUE TITLE
LSM9DS1 Smooth and accurate AHRS

### ISSUE THREAD

**Issue by meisamsafavi** [adafruit/Adafruit_AHRS#24]
Hi,
First of all I want to appreciate Adafurit for such incredible products and libraries, and a special thanks for Adafruit AHRS Kalman library, implementing the original NXP library is a nightmare.
I have been working with IMUs for a long time, and I used Adafruit BNO055 and Adafruit LSM9DS1 and lots of other sensor boards in my previous projects.I think the BNO sensor is a masterpiece but as you know you don't have access to source code nor matrices, so there is no possibility to manipulate the output.
Having manipulation limitations on BNO I decided to use LSM9DS1, Now that I'm using it with the Adafruit AHRS library, the results are outstanding. Comparing BNO and LSM9DS1 outputs, LSM is a little bit shaky and unstable, so I decided to make some adjustments in library definitions, for example various noise constants and filter frequency, I also tried different ODR and FS setting on sensor but it had no noticeable effect.
So I decided to ask to community:
What exact setting should be set for sensor?
Which frequency should I run the filter?
What should I do rather than above ones to get perfect and smooth output like BNO?
also I will be happy for any advice from another perspectives.

Best Regards,
Mason

**Comment by ladyada** [comment]
hiya github issues are for bug reports - for tech support questions please post on forums or discord. thanks!
