### ISSUE TITLE
Adafruit_Sensor_Calibration.h dependency not shown in Arduino Library Manager

### ISSUE THREAD

**Issue by BenJSpearman** [adafruit/Adafruit_AHRS#8]
- Arduino board:  Any

- Arduino IDE version:  1.8.11

Adafruit Sensor Calibration simply does not show up as a dependency when attempting to download the library from the Arduino Library Manager. Further inspection shows that the Adafruit Sensor Calibration library does not currently exist in the arduino library manager, but this may just be due to it being created so shortly ago.

**Comment by ladyada** [comment]
correct - https://github.com/arduino/Arduino/issues/9707

**Comment by ladyada** [comment]
please install manually for now!
